export enum WheelBrand {
  NO_BRAND = 'NO_BRAND',
  ALDER = 'Alder',
  ARNIDA = 'Arnida',
  AUTOBELLO = 'Autobello',
  BETA = 'Beta',
  BRUCKELL = 'Bruckell',
  CHERRIER = 'Cherrier',
  CIVETTA = 'Civetta',
  CLOCKWISE = 'Clockwise',
  DREID = 'Dreid',
  ETK = 'ETK',
  FOLK = 'Folk',
  GAVRIL = 'Gavril',
  GP = 'GP',
  GRIP_ALL = 'Grip-All',
  HIROSHI = 'Hiroch',
  IBISHU = 'Ibishu',
  LEGNO = 'Legno',
  OKUDAI = 'Okudai',
  SOLIAD = 'Soliad',
  SP = 'SP',
  STX = 'STX',
  TIMS = 'TIMS',
  TRIAL = 'Trial',
  WANGAN = 'Wangan',
}
